### ISSUE TITLE
Tangut Displays □ 

### ISSUE THREAD

**Issue by Vipza72130** [Hulenkius/rime_tangutcjkk#1]
Hi ! Everything works except for the display that doesn't show the caracter but blank unicode box : 

![image](https://github.com/Hulenkius/rime_tangutcjkk/assets/159253070/c5332d71-aca6-4fae-be0d-7400004b2ec9)

Do you know a way to fix this ?
Thanks

**Comment by Hulenkius** [comment]
thanks for your attention

you will need a proper font to display tangut glyphs, such as Tangut Yinchuan, Noto Serif Tangut, etc.

here follows a link for the file of Noto Serif Tangut:
https://drive.google.com/file/u/0/d/1KYDYfZc5d8hqFGhgTFRshKuArbKQOC-U/view?usp=sharing&pli=1

by downloading the file, you could just double-click on it, and click on the "install" button on the up-left corner of the font preview window.

after installing the font, reboot your pc, and it should be fine.

**Comment by Hulenkius** [comment]
noticing that your pc can normally display tangut glyphs in that firefox search bar, it means your pc should be equipped with some tangut fonts.

you can open `tangutcjkk.schema.yaml` and turn to Line 70, then replace the existing font setting with the name of your installed font(s).

then right-click on the "㞢" button on the right side of your task bar, and click "重新部署"(is this the text? idk). then it should work fine too.

**Comment by Vipza72130** [comment]
Thank you for your quick answers ! I alreday have both Noto Serif Tangut & Tangut Yinchuan.
I tried what you told me in your second post but it doesn't change anything...

**Comment by Hulenkius** [comment]
try this:
![-1822520c472cd466](https://github.com/Hulenkius/rime_tangutcjkk/assets/32562298/3dce25ed-76bb-4104-8adf-c5d3dbc88e43)

**Comment by Vipza72130** [comment]
It worked !!!! Thank you so so much !!
